PROMETHEUS_VERSION=${PROMETHEUS_VERSION:-2.7.1}
ALERTMANAGER_RELEASE=${ALERTMANAGER_RELEASE:-0.16.1}
NODE_EXPORTER_RELEASE=${NODE_EXPORTER_RELEASE:-0.17.0}
CLOUDWATCH_EXPORTER_RELEASE=${CLOUDWATCH_EXPORTER_RELEASE:-0.5.0}
YACE_CLOUDWATCH_EXPORTER_RELEASE=${YACE_CLOUDWATCH_EXPORTER_RELEASE:-0.12.0}
